# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

	pod 'React', :path => '../node_modules/react-native'
	pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end